name: Check style, test

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  check3_11:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black
        python -m pip install flake8
        python -m pip install mypy
        python -m pip install pytest
        python -m pip install types-PyYAML>=6.0.1
        python -m pip install types-paramiko
        python -m pip install -r requirements.txt
    - name: Check code formatting with Black
      run: |
       black --version
       black --check --diff .
    - name: flake8
      run: |
       flake8 --version
       flake8
    - name: Type check with Mypy
      run: |
       mypy --version
       mypy --strict --config-file mypy.ini .
    - name: Run tests with Pytest
      run: |
       pytest --version
       pytest

  check3_9:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black==22.12.0
        python -m pip install flake8
        python -m pip install mypy
        python -m pip install pytest
        python -m pip install types-PyYAML>=6.0.1
        python -m pip install types-paramiko
        python -m pip install -r requirements.txt
    - name: Check code formatting with Black
      run: |
       black --version
       black --check --diff .
    - name: flake8
      run: |
       flake8 --version
       flake8
    - name: Type check with Mypy
      run: |
       mypy --version
       mypy --strict --config-file mypy.ini ktoolbox/
    - name: Run tests with Pytest
      run: |
       pytest --version
       pytest ktoolbox/
